/*How many orders are Delivered, Shipped, and Cancelled?*/
SELECT 
	o.status, count(*) as orders_count
FROM orders o
GROUP BY o.status
ORDER BY orders_count;


 /* What is the total revenue generated by the company? */
SELECT 
	SUM(p.price * oi.quantity) AS Total_Revenue
FROM orders o
JOIN order_items oi
	ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status != 'Cancelled';  



/*Which product category generates the most revenue?*/
SELECT 
	p.category, SUM(p.price * oi.quantity) as most_revenue
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
JOIN orders o
	ON oi.order_id = o.order_id
WHERE o.status != 'Cancelled'	
GROUP BY p.category
ORDER BY most_revenue desc;


/*How does revenue change month by month?*/
SELECT 
	strftime('%Y-%m', o.order_date) as monthly_sales,
	sum(p.price * oi.quantity) as monthly_revenue
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
JOIN orders o
	ON oi.order_id = o.order_id
WHERE o.status != 'Cancelled'
GROUP BY monthly_sales
ORDER BY monthly_sales;

/*What is the average revenue generated per non-cancelled order?*/
SELECT 
	strftime('%Y-%m', o.order_date) as monthly_sales,
	round(SUM(p.price * oi.quantity) * 1.0 / COUNT(DISTINCT o.order_id), 2) AS average_order_value
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status != 'Cancelled'
GROUP BY monthly_sales
ORDER BY monthly_sales;


/*How many orders are being cancelled, and what percentage of all orders does that represent?*/
SELECT 
	count(*) as total_orders,
	count(CASE WHEN status = 'Cancelled' THEN 1 END) as cancelled_orders,
	count(CASE WHEN status = 'Cancelled' THEN 1 END) * 100 / count(*) as cancellation_rate 
FROM orders;
